export default function Head() {
  return (
    <>
      <title>Step07 Tailwind Hello World (hassan-ak)</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
